# Generated by Django 4.2.13 on 2025-04-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_At',
            new_name='create_at',
        ),
    ]
