# Generated by Django 4.2.13 on 2025-04-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_create_at_task_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
